### ISSUE TITLE
 ERROR [ExceptionHandler] password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by lcsml** [CATProtocol/cat-token-box#145]
Having an error with password authentication failed issue when connecting to "postgres"
[Nest] 29  - 09/28/2024, 8:31:23 PM   ERROR [ExceptionHandler] password authentication failed for user "postgres"
error: password authentication failed for user "postgres"
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.22
$ node dist/main

**Below is the docker-compose.yml config**
services:
  postgres:
    image: postgres:16
    shm_size: 1g
    restart: always
    environment:
     # POSTGRES_USER: $DATABASE_USERNAME
     # POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_DB
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data

  bitcoind:
    image: fractalbitcoin/fractal:v0.2.1
    restart: always
    entrypoint: ["bitcoind", "-datadir=/data/", "-maxtipage=504576000"]
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data/", "getblockchaininfo"]
    ports:
      - "8330:8330"
      - "8331:8331"
      - "8332:8332"
      - "8333:8333"
    deploy:
      resources:
        limits:
          memory: 40G
    memswap_limit: 60G
    mem_swappiness: 100
    volumes:
      - ./docker/data:/data
    logging:
      driver: "json-file"
      options:
        labels: "env,filebeat,name"
        max-size: "1g"
        max-file: "3"

**Comment by opcatdev** [comment]
you commented out on these 2 lines

```
environment:
# POSTGRES_USER: $DATABASE_USERNAME
# POSTGRES_PASSWORD: $DATABASE_PASSWORD
```
