### ISSUE TITLE
Cannot find the artifact file for contract 

### ISSUE THREAD

**Issue by bupabupala** [CATProtocol/cat-token-box#6]
docker logs -f tracker 
yarn run v1.22.22
$ node dist/main
/app/node_modules/scrypt-ts/dist/smart-contract/contract.js:144
            throw new Error(`Cannot find the artifact file for contract \`${this.name}\`, run \`npx scrypt-cli@latest compile\` to generate it.`);
            ^

Error: Cannot find the artifact file for contract `ClosedMinter`, run `npx scrypt-cli@latest compile` to generate it.
    at ClosedMinter.loadArtifact (/app/node_modules/scrypt-ts/dist/smart-contract/contract.js:144:19)
    at /app/packages/smartcontracts/dist/index.js:24:33
    at Object.<anonymous> (/app/packages/smartcontracts/dist/index.js:29:3)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/packages/tracker/dist/services/tx/tx.service.js:28:30)

Node.js v20.17.0
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
yarn run v1.22.22
$ node dist/main
/app/node_modules/scrypt-ts/dist/smart-contract/contract.js:144
            throw new Error(`Cannot find the artifact file for contract \`${this.name}\`, run \`npx scrypt-cli@latest compile\` to generate it.`);
            ^

Error: Cannot find the artifact file for contract `ClosedMinter`, run `npx scrypt-cli@latest compile` to generate it.
    at ClosedMinter.loadArtifact (/app/node_modules/scrypt-ts/dist/smart-contract/contract.js:144:19)
    at /app/packages/smartcontracts/dist/index.js:24:33
    at Object.<anonymous> (/app/packages/smartcontracts/dist/index.js:29:3)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/packages/tracker/dist/services/tx/tx.service.js:28:30)

Node.js v20.17.0
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.

**Comment by opcatbugcloser** [comment]
Please run `yarn install && yarn build`

**Comment by xiaosongfu** [comment]
execute `yarn build` at project's root dir, report this error:

```
@cat-protocol/cat-smartcontracts:build: Error: Cannot find module 'D:\dev\202409-cat\cat-token-box\node_modules\node_modules\scrypt-cli\src\bin\index.js'
@cat-protocol/cat-smartcontracts:build:     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
@cat-protocol/cat-smartcontracts:build:     at Module._load (node:internal/modules/cjs/loader:1051:27)
@cat-protocol/cat-smartcontracts:build:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
@cat-protocol/cat-smartcontracts:build:     at node:internal/main/run_main_module:28:49 {
@cat-protocol/cat-smartcontracts:build:   code: 'MODULE_NOT_FOUND',
@cat-protocol/cat-smartcontracts:build:   requireStack: []
@cat-protocol/cat-smartcontracts:build: }
```

how to fix it? 

thanks @opcatbugcloser

**Comment by yadgen** [comment]
@opcatbugcloser 
I met the same problem, when I executed the order `yarn install && yarn build,` although it was successful, it was still wrong!
Error: cannot find the artifact file for contract closedminter, run NPX scrypt-cli@latest compile' to generate it.
![image](https://github.com/user-attachments/assets/92fc22bb-e5e4-47ec-bfb9-c02d9897bf64)

**Comment by yadgen** [comment]
@opcatbugcloser hello?
