### ISSUE TITLE
yarn cli wallet create 报错 哪个大佬能帮看下，ubuntu 没问题，windows 就会报这个错

### ISSUE THREAD

**Issue by xianquan3230** [CATProtocol/cat-token-box#79]
yarn cli wallet export --create=true
yarn run v1.22.22
$ node dist/main wallet export --create=true
E:\dev\cat-token-box-main\node_modules\scrypt-ts\dist\smart-contract\contract.js:144
            throw new Error(`Cannot find the artifact file for contract \`${this.name}\`, run \`npx scrypt-cli@latest compile\` to generate it.`);
            ^

Error: Cannot find the artifact file for contract `ClosedMinter`, run `npx scrypt-cli@latest compile` to generate it.
    at ClosedMinter.loadArtifact (E:\dev\cat-token-box-main\node_modules\scrypt-ts\dist\smart-contract\contract.js:144:19)
    at E:\dev\cat-token-box-main\packages\smartcontracts\dist\index.js:24:33
    at Object.<anonymous> (E:\dev\cat-token-box-main\packages\smartcontracts\dist\index.js:29:3)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (E:\dev\cat-token-box-main\packages\cli\dist\common\apis-tracker.js:4:30)

Node.js v20.17.0
error Command failed with exit code 1.

**Comment by somethingbeta** [comment]
you tried this?

run npx scrypt-cli@latest compile

**Comment by xianquan3230** [comment]
NPX scrypt-cli@latest compile

**Comment by xianquan3230** [comment]
执行过了NPX scrypt-cli@latest compile
还是有这个问题

**Comment by xianquan3230** [comment]
npx scrypt-cli@latest compile
- Building TS...

error TS18003: No inputs were found in config file 'E:/dev/cat-token-box-main/tsconfig-scryptTS.json'. Specified 'include' paths were '["src/contracts/**/*.ts"]' and 'exclude' paths were '[]'.
  undefined
× Building TS
ERROR: Building TS failed!
Please modify your code or `tsconfig-scryptTS.json` according to the error message output during BUILDING.
执行命令报这个错
